### ISSUE TITLE
Chomiteca 2.0 no found kodi 19.5/20.1

### ISSUE THREAD

**Issue by Deci8BelioS** [Leinad4Mind/leinad4mind-addons#15]
when configuring the account and opening the addon, the following error occurs

2023-04-20 20:24:02.281 T:2344    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 5 arguments (6 given)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1204, in <module>
                                                       if (selfAddon.getSetting('chomikuj-enable') == 'true' and not selfAddon.getSetting('chomikuj-username')== '') : login()
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 67, in login
                                                       opcao= xbmcgui.Dialog().yesno(label[x], traducao(40005), "", "",traducao(40006), 'OK')
                                                   TypeError: function takes at most 5 arguments (6 given)
                                                   -->End of Python script error report<--

**Comment by Leinad4Mind** [comment]
Will take a look. Only tested on 18 and 19.
Let see 20.1... Thanks for reporting

**Comment by Deci8BelioS** [comment]
> Will take a look. Only tested on 18 and 19. Let see 20.1... Thanks for reporting

I have tried it on kodi 19, 19.5 and 20.1 without success.

**Comment by Leinad4Mind** [comment]
New release available. Should fix all the issues.

**Comment by Deci8BelioS** [comment]
> New release available. Should fix all the issues.

When trying to play mkv files it throws this error:

2023-04-20 23:07:06.161 T:10048   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'str' object is not callable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1224, in <module>
                                                       elif mode==4: analyzer(url)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 705, in analyzer
                                                       endereco=subtitles(fileid,url)
                                                   TypeError: 'str' object is not callable
                                                   -->End of Python script error report<--

**Comment by Deci8BelioS** [comment]
this error occurs when trying to play an .mp3

2023-04-20 23:13:50.467 T:13068   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'liz' is not defined
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1224, in <module>
                                                       elif mode==4: analyzer(url)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 710, in analyzer
                                                       else: startvideo(name,linkfinal,playterm=playterm)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 780, in startvideo
                                                       liz.setArt({"icon": "DefaultImage.png", "thumb": thumb})
                                                   NameError: name 'liz' is not defined
                                                   -->End of Python script error report<--

**Comment by Deci8BelioS** [comment]
this error pops up when trying to play an ISO (I guess extension not playable by KODI)

2023-04-20 23:15:48.886 T:5272    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (3 given)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1224, in <module>
                                                       elif mode==4: analyzer(url)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 712, in analyzer
                                                       if selfAddon.getSetting('aviso-extensao') == 'true': messageok(sitename,translation(40028),translation(40029) + translation(40030))
                                                   TypeError: function takes at most 2 arguments (3 given)
                                                   -->End of Python script error report<--

**Comment by Leinad4Mind** [comment]
Ok, I just tried to logged in and enter on the pages. Let see.

**Comment by Deci8BelioS** [comment]
Adding to the library throws this error in the log, nothing appears in kodi

2023-04-20 23:22:21.981 T:2004    error <general>: C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py:430: DeprecationWarning: The unescape method is deprecated and will be removed in 3.5, use html.unescape() instead.
                                                     filetitle = h.unescape(name[0].replace('<span class="e">','').replace(' </span>',''))
                                                     
Thank you very much for your work <3

**Comment by Leinad4Mind** [comment]
All those fixed. And I found other problems too. New 2.2.2 version released. Please check out.

**Comment by Deci8BelioS** [comment]
At the moment it plays mkv's fine, it works fine to open from .strm, but the add to library is not working, in the log I only see this but I don't know if it has something to do with the script function:

2023-04-21 04:38:12.007 T:11232 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.

I have modified the icons of the addon and the info of addon.xml, added that it detects the .mkv files to put its icon and also the .exe files, I would like to pass them to you to add it in the official version of the addon.

Spanish language in the addon interface for some reason is not being applied, English is.

**Comment by Leinad4Mind** [comment]
Send me a private message on the forum with the changes. Thanks

**Comment by Deci8BelioS** [comment]
sent

**Comment by Leinad4Mind** [comment]
I refactored almost all functions, and did a good cleanup and added your changes.

**Comment by Deci8BelioS** [comment]
this error occurs when using the download option:

                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1228, in <module>
                                                       elif mode==11: analyzer(url,subs='',playterm='download')
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 700, in analyzer
                                                       else: startvideo(name,linkfinal,playterm=playterm,subtitles=address)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 722, in startvideo
                                                       createdownlad(name,url)
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\chomiteca.py", line 1066, in createdownlad
                                                       from resources.lib import downloader
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\resources\lib\downloader.py", line 9, in <module>
                                                       iconsmall = os.path.join(xbmcaddon.Addon(id='plugin.video.chomiteca').getAddonInfo('path').decode('utf-8'),'resources','art','iconpq.png')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

**Comment by Leinad4Mind** [comment]
Just remove .decode('utf-8') from lib\downloader.py and let me know

**Comment by Deci8BelioS** [comment]
2023-04-21 20:29:52.924 T:4044    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: decoding str is not supported
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\resources\lib\downloader.py", line 204, in <module>
                                                       doDownload(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\resources\lib\downloader.py", line 94, in doDownload
                                                       dialogDL=dialogCompatible() #dialog available on gotham++
                                                     File "C:\Users\DeciBelioS\AppData\Roaming\Kodi\addons\plugin.video.chomiteca\resources\lib\downloader.py", line 193, in dialogCompatible
                                                       json_query = str(json_query, 'utf-8', errors='ignore')
                                                   TypeError: decoding str is not supported
                                                   -->End of Python script error report<--

**Comment by Deci8BelioS** [comment]
I have back to translate from 0 to Spanish using the English one as a base and now if the translation is well applied, I leave it to you by PM on the web if you want to implement it.

**Comment by Leinad4Mind** [comment]
I've in the meanwhile fixed the download (at least sort of lol) and make the notifications to work again
Leave me there so I can add it on the next release

**Comment by Leinad4Mind** [comment]
See trailers needs a new google api key... I dont want to create a new one... feeling lazy

**Comment by Deci8BelioS** [comment]
I don't use that at least, but to make it easier you could add the option to put the api key in the addon configuration.

Is it possible to add continue watching?

And when I open a movie from the .strm (from the kodi menu) the movie title appears File.aspx, if I open it from the addon browser the title appears fine.

I have a script to scrape the movies and series in javascript as chomiteca does (somewhat improved) I don't know if you could use it if you want to improve the script scraper.

**Comment by Deci8BelioS** [comment]
Ok the title of the movie File.aspx is because in the .strm files it doesn't have at the end "&name=" that I didn't know how to add it in the javascript script to export it.

**Comment by Leinad4Mind** [comment]
> I don't use that at least, but to make it easier you could add the option to put the api key in the addon configuration.

Thanks for the idea!

> And when I open a movie from the .strm (from the kodi menu) the movie title appears File.aspx, if I open it from the addon browser the title appears fine.

Can you remind me what is the strm, Its been some years I dont touch kodi xD
How can I test this?

**Comment by Deci8BelioS** [comment]
.strm files contain something like this

plugin://plugin.video.chomiteca/?url=https://chomikuj.pl/

I have already solved the File.aspx name thing, as I use my own scraper it didn't add the title in the url so that the addon can read it and know what movie it is.

**Comment by Leinad4Mind** [comment]
Ah I see. Seems to be good then:

 strm_contents = 'plugin://plugin.video.chomiteca/?url=' + url +'&mode=25&name=' + urllib.parse.quote_plus(title)

**Comment by Deci8BelioS** [comment]
in javascript I have it set like this

var fileContent = "plugin://plugin.video.chomiteca/?url=https://chomikuj.pl" + link + '&mode=25&name=' + encodeURIComponent(fileName.substring(0, fileName.lastIndexOf("."))); 

to take directly the name of the .strm file xd

**Comment by Leinad4Mind** [comment]
2.3.2 released, please check

I've added the trailer option for adding google api key

**Comment by Deci8BelioS** [comment]
So far everything seems to be working, I'll send you the Spanish translation by PM (I don't know why I had to translate it again using English as a base)

**Comment by Deci8BelioS** [comment]
Do you think it is possible to make the addon work through the kodi web interface, I can browse the chomiteca directory from the kodi web interface but it does not play in the browser, if it can not be done nothing happens it was in case you saw it viable.

**Comment by Leinad4Mind** [comment]
I don't think its possible via plugin only. For what I check you would need to have flask, and serve an special web interface for the plugin. Not something that I would invest my time honestly.

**Comment by Deci8BelioS** [comment]
No problem then, I was just saying it in case it was feasible, also thank you for solving the addon problems in the latest version of kodi <3, if for whatever reason you want ideas to implement the addon I have a few xddd

**Comment by Leinad4Mind** [comment]
Create a new issue with the ideas you may have. I'll close this one.
